package uz.mediasolutions.taxiservicebot.payload;

public enum BotState {

    ENTER,
    START,
    DRIVER_FIO,
    DRIVER_PHONE_1,
    DRIVER_PHONE_2,
    CAR_MODEL,
    CAR_NUMBER,
    PASSENGER_PHONE,
    PASSENGER_COUNT_OR_DELIVERY,
    DRIVER_REGISTRATION_FINISHED,
    PASSENGER_REGISTRATION_FINISHED,
    TOUR_INFO_FINISHED,
    CHOOSE_ROLE,
    MENU_OR_TAXI_BOOK,
    AT_TA,
    TOUR_TIME,
    BACK_OR_CONFIRM_PAYMENT,
    MENU_OR_CONFIRM_PAYMENT,
    BACK_OR_TAXI_BOOK,
    USER_FIO,
    INCORRECT_DRIVER_PHONE_1,
    INCORRECT_DRIVER_PHONE_2,
    INCORRECT_USER_PHONE,
    ACCEPT_REJECT_SCREENSHOT,
    MENU_OR_DECLINE_ORDER_OR_CONTINUE,
    PASSENGER_MENU,
    INCORRECT_PHOTO_SIZE,
    DRIVER_MENU,
    SEND_SCREENSHOT,
    FOR_ADMINS

}
